[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "https://ks5stj5f5bqcw235o2gehbcz5q0estdg.lambda-url.us-east-1.on.aws/:splat"
status = 200
force = true

[build]
publish = "./dist"
command = "yarn build"
