[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/search/*"
to = "https://hbkdhwaic4is7kimo2c72r5i7q0pqjik.lambda-url.us-east-1.on.aws//:splat"
status = 200
force = true

[build]
publish = "./dist"
command = "yarn build"
