// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clock: typeof import('./components/Clock.vue')['default']
    Crawler: typeof import('./components/Crawler.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    Dock: typeof import('./components/Dock.vue')['default']
    ElasticSearch: typeof import('./components/ElasticSearch.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Ico: typeof import('./components/Ico.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    ThreeSlider: typeof import('./components/ThreeSlider.vue')['default']
  }
}
